const chineseVocabulary = [
    {
        "word":"单身",
        "pinyin":"dānshēn",
        "englishTranslation":null,
        "spanishTranslation":"soltero/a",
        "example":""
    },
    {
        "word":"已婚",
        "pinyin":"yǐhūn",
        "englishTranslation":null,
        "spanishTranslation":"casado/a",
        "example":""
    },
    {
        "word":"居",
        "pinyin":"jū",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"分居",
        "pinyin":"fēnjū",
        "englishTranslation":null,
        "spanishTranslation":"separarse de vivienda",
        "example":""
    },
    {
        "word":"分开",
        "pinyin":"fēnkāi",
        "englishTranslation":null,
        "spanishTranslation":"separarse",
        "example":""
    },
    {
        "word":"妻子",
        "pinyin":"qīzi",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"鳏夫",
        "pinyin":"",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"丈夫",
        "pinyin":"zhàngfu",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"寡妇",
        "pinyin":"",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"黑寡妇",
        "pinyin":"",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"市场",
        "pinyin":"shìchǎng",
        "englishTranslation":null,
        "spanishTranslation":"mercado",
        "example":""
    },
    {
        "word":"营",
        "pinyin":"yíng",
        "englishTranslation":null,
        "spanishTranslation":"gestión, gestionar",
        "example":""
    },
    {
        "word":"销",
        "pinyin":"xiāo",
        "englishTranslation":null,
        "spanishTranslation":"venta",
        "example":""
    },
    {
        "word":"父亲",
        "pinyin":"fùqīn",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"母亲",
        "pinyin":"mǔqīn",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"父母",
        "pinyin":"fùmǔ",
        "englishTranslation":null,
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"已经",
        "pinyin":"yǐjīng",
        "englishTranslation":"already",
        "spanishTranslation":"ya",
        "example":""
    },
    {
        "word":"退休",
        "pinyin":"tuìxiū",
        "englishTranslation":null,
        "spanishTranslation":"retirarse, jubilarse",
        "example":""
    },
    {
        "word":"车",
        "pinyin":"chē",
        "englishTranslation":null,
        "spanishTranslation":"coche, vehículo",
        "example":""
    },
    {
        "word":"词典",
        "pinyin":"cídiǎn",
        "englishTranslation":null,
        "spanishTranslation":"diccionario",
        "example":""
    },
    {
        "word":"电脑",
        "pinyin":"diànnǎo",
        "englishTranslation":null,
        "spanishTranslation":"computadora",
        "example":""
    },
    {
        "word":"孩子",
        "pinyin":"háizi",
        "englishTranslation":null,
        "spanishTranslation":"niño",
        "example":""
    },
    {
        "word":"爷爷",
        "pinyin":"yéye",
        "englishTranslation":null,
        "spanishTranslation":"abuelo paterno",
        "example":""
    },
    {
        "word":"外公",
        "pinyin":"wàigōng",
        "englishTranslation":null,
        "spanishTranslation":"abuelo materno",
        "example":""
    },
    {
        "word":"系主任",
        "pinyin":"xìzhǔrèn",
        "englishTranslation":null,
        "spanishTranslation":"jefe de departamento",
        "example":""
    },
    {
        "word":"助教",
        "pinyin":"zhùjiào",
        "englishTranslation":null,
        "spanishTranslation":"ayudante de profesor",
        "example":""
    },
    {
        "word":"律师",
        "pinyin":"lǜshī",
        "englishTranslation":null,
        "spanishTranslation":"abogado",
        "example":""
    },
    {
        "word":"工程师",
        "pinyin":"gōngchéngshī",
        "englishTranslation":null,
        "spanishTranslation":"ingeniero",
        "example":""
    },
    {
        "word":"大",
        "pinyin":"dà",
        "englishTranslation":null,
        "spanishTranslation":"grande, voluminoso",
        "example":""
    },
    {
        "word":"多少",
        "pinyin":"duōshao",
        "englishTranslation":null,
        "spanishTranslation":"cuántos",
        "example":""
    },
    {
        "word":"多",
        "pinyin":"duō",
        "englishTranslation":null,
        "spanishTranslation":"mucho",
        "example":""
    },
    {
        "word":"少",
        "pinyin":"shǎo",
        "englishTranslation":null,
        "spanishTranslation":"poco",
        "example":""
    },
    {
        "word":"外",
        "pinyin":"wài",
        "englishTranslation":null,
        "spanishTranslation":"extranjero",
        "example":""
    },
    {
        "word":"外国",
        "pinyin":"wàiguó",
        "englishTranslation":null,
        "spanishTranslation":"país extranjero",
        "example":""
    },
    {
        "word":"百",
        "pinyin":"bǎi",
        "englishTranslation":null,
        "spanishTranslation":"cien",
        "example":""
    },
    {
        "word":"想",
        "pinyin":"xiǎng",
        "englishTranslation":null,
        "spanishTranslation":"desear, pensar",
        "example":""
    },
    {
        "word":"我想...",
        "pinyin":"wǒxiǎng",
        "englishTranslation":null,
        "spanishTranslation":"me gustaría..., pienso....",
        "example":""
    },
    {
        "word":"甜点",
        "pinyin":"tiándiǎn",
        "englishTranslation":null,
        "spanishTranslation":"postre, dulces",
        "example":""
    },
    {
        "word":"甜",
        "pinyin":"tián",
        "englishTranslation":null,
        "spanishTranslation":"dulce",
        "example":""
    },
    {
        "word":"点",
        "pinyin":"diǎn",
        "englishTranslation":null,
        "spanishTranslation":"punto",
        "example":""
    },
    {
        "word":"布丁",
        "pinyin":"bùdīng",
        "englishTranslation":null,
        "spanishTranslation":"flan",
        "example":""
    },
    {
        "word":"杯子蛋糕",
        "pinyin":"bēizi dàngāo",
        "englishTranslation":"cupcake",
        "spanishTranslation":"",
        "example":""
    },
    {
        "word":"蛋糕",
        "pinyin":"dàngāo",
        "englishTranslation":null,
        "spanishTranslation":"torta",
        "example":""
    },
    {
        "word":"糕",
        "pinyin":"gāo",
        "englishTranslation":null,
        "spanishTranslation":"pastel",
        "example":""
    },
    {
        "word":"狗",
        "pinyin":"gǒu",
        "englishTranslation":null,
        "spanishTranslation":"perro/a",
        "example":""
    },
    {
        "word":"猫",
        "pinyin":"māo",
        "englishTranslation":null,
        "spanishTranslation":"gato/a",
        "example":""
    },
    {
        "word":"只",
        "pinyin":"zhī",
        "englishTranslation":null,
        "spanishTranslation":"clasificador de animal",
        "example":"一只狗，两只猫"
    },
    {
        "word":"白",
        "pinyin":"bái",
        "englishTranslation":null,
        "spanishTranslation":"blanco/a",
        "example":"一只白狗，白巧克力"
    },
    {
        "word":"黑",
        "pinyin":"hēi",
        "englishTranslation":null,
        "spanishTranslation":"negro/a",
        "example":"两只黑狗，四只黑猫，黑咖啡，黑巧克力，黑啤酒"
    },
    {
        "word":"家",
        "pinyin":"jiā",
        "englishTranslation":null,
        "spanishTranslation":"familia, hogar",
        "example":"我们家，你们家，他们家"
    },
    {
        "word":"口",
        "pinyin":"kǒu",
        "englishTranslation":null,
        "spanishTranslation":"clasificador usado principalmente para referirse al número de miembros de una familia",
        "example":""
    },
    {
        "word":"照片",
        "pinyin":"zhàopiàn",
        "englishTranslation":null,
        "spanishTranslation":"fotografía",
        "example":"我的照片，我们家的照片"
    },
    {
        "word":"和",
        "pinyin":"hé",
        "englishTranslation":null,
        "spanishTranslation":"y",
        "example":"爸爸和妈妈，哥哥和我，你和他"
    },
    {
        "word":"个",
        "pinyin":"gè",
        "englishTranslation":null,
        "spanishTranslation":"clasificador de uso general",
        "example":"几个弟弟，一个朋友，五个医生，七个学院，九个系"
    },
    {
        "word":"两",
        "pinyin":"liǎng",
        "englishTranslation":null,
        "spanishTranslation":"dos",
        "example":"两口人，两个姐姐，两个老师，两个系"
    },
    {
        "word":"还",
        "pinyin":"hái",
        "englishTranslation":null,
        "spanishTranslation":"además",
        "example":"还有，还要，还认识，还学习"
    },
    {
        "word":"一共",
        "pinyin":"yígòng",
        "englishTranslation":null,
        "spanishTranslation":"en total",
        "example":"一共有六口人"
    },
    {
        "word":"小",
        "pinyin":"xiǎo",
        "englishTranslation":null,
        "spanishTranslation":"pequeño",
        "example":"小弟弟，小妹妹"
    },
    {
        "word":"张",
        "pinyin":"zhāng",
        "englishTranslation":null,
        "spanishTranslation":"clasificador de objetos planos",
        "example":"两张照片，一张名片"
    },
    {
        "word":"真",
        "pinyin":"zhēn",
        "englishTranslation":null,
        "spanishTranslation":"realmente/real",
        "example":"真的，真忙，真高兴，真有意思"
    },
    {
        "word":"可爱",
        "pinyin":"kě'ài",
        "englishTranslation":null,
        "spanishTranslation":"adorable, agradable",
        "example":"真可爱，可爱的照片"
    },
    {
        "word":"爱",
        "pinyin":"ài",
        "englishTranslation":null,
        "spanishTranslation":"amar",
        "example":"爱爸爸，爱妈妈，爱弟弟妹妹"
    },
    {
        "word":"没",
        "pinyin":"méi",
        "englishTranslation":null,
        "spanishTranslation":"no",
        "example":"没有"
    },
    {
        "word":"快乐",
        "pinyin":"kuàilè",
        "englishTranslation":null,
        "spanishTranslation":"feliz",
        "example":""
    },
    {
        "word":"快",
        "pinyin":"kuài",
        "englishTranslation":null,
        "spanishTranslation":"rápido/a",
        "example":"很快，太快了，快餐，快餐厅"
    },
    {
        "word":"为什么",
        "pinyin":"wèi shénme",
        "englishTranslation":null,
        "spanishTranslation":"¿por qué?",
        "example":"为什么你不喝咖啡加牛奶?"
    },
    {
        "word":"为",
        "pinyin":"wèi",
        "englishTranslation":null,
        "spanishTranslation":"por",
        "example":""
    },
    {
        "word":"因为",
        "pinyin":"yīnwèi",
        "englishTranslation":null,
        "spanishTranslation":"porque",
        "example":"因为我不喜欢牛奶"
    },
    {
        "word":"踢足球",
        "pinyin":"tīzúqiú",
        "englishTranslation":null,
        "spanishTranslation":"jugar fútbol",
        "example":""
    },
    {
        "word":"踢",
        "pinyin":"tī",
        "englishTranslation":null,
        "spanishTranslation":"patear",
        "example":""
    },
    {
        "word":"足",
        "pinyin":"zú",
        "englishTranslation":null,
        "spanishTranslation":"pie",
        "example":""
    },
    {
        "word":"足球",
        "pinyin":"zúqiú",
        "englishTranslation":null,
        "spanishTranslation":"fútbol",
        "example":""
    },
    {
        "word":"可是",
        "pinyin":"kěshì",
        "englishTranslation":null,
        "spanishTranslation":"pero",
        "example":""
    },
    {
        "word":"高尔夫球",
        "pinyin":"gāo´ěr fū qiú",
        "englishTranslation":null,
        "spanishTranslation":"golf",
        "example":""
    },
    {
        "word":"行",
        "pinyin":"xíng",
        "englishTranslation":null,
        "spanishTranslation":"poder, vale, dale, estar bien",
        "example":""
    },
    {
        "word":"好喝",
        "pinyin":"hǎohē",
        "englishTranslation":null,
        "spanishTranslation":"rico/a (para las bebidas)",
        "example":"姐姐说巴西咖啡很好喝，但是美国咖啡不好喝"
    },
    {
        "word":"什么时候",
        "pinyin":"shénme shíhòu",
        "englishTranslation":null,
        "spanishTranslation":"¿cuándo?",
        "example":""
    },
    {
        "word":"什么",
        "pinyin":"shénme",
        "englishTranslation":null,
        "spanishTranslation":"¿qué?",
        "example":""
    },
    {
        "word":"时候",
        "pinyin":"shíhou",
        "englishTranslation":null,
        "spanishTranslation":"momento",
        "example":"我们什么时候去星巴克喝咖啡?"
    },
    {
        "word":"现在",
        "pinyin":"xiànzài",
        "englishTranslation":null,
        "spanishTranslation":"ahora",
        "example":"现在去"
    },
    {
        "word":"打球",
        "pinyin":"dǎqiú",
        "englishTranslation":null,
        "spanishTranslation":"jugar a la pelota",
        "example":""
    },
    {
        "word":"打",
        "pinyin":"dǎ",
        "englishTranslation":null,
        "spanishTranslation":"jugar",
        "example":""
    },
    {
        "word":"球",
        "pinyin":"qiú",
        "englishTranslation":null,
        "spanishTranslation":"pelota",
        "example":""
    },
    {
        "word":"网球",
        "pinyin":"wǎngqiú",
        "englishTranslation":null,
        "spanishTranslation":"tenis",
        "example":""
    },
    {
        "word":"网",
        "pinyin":"wǎng",
        "englishTranslation":null,
        "spanishTranslation":"red",
        "example":""
    },
    {
        "word":"上网",
        "pinyin":"shàngwǎng",
        "englishTranslation":null,
        "spanishTranslation":"navegar en el internet",
        "example":""
    },
    {
        "word":"网上",
        "pinyin":"wǎngshàng",
        "englishTranslation":null,
        "spanishTranslation":"en el internet",
        "example":""
    },
    {
        "word":"打网球",
        "pinyin":"dǎwǎngqiú",
        "englishTranslation":null,
        "spanishTranslation":"jugar tenis",
        "example":""
    },
    {
        "word":"对",
        "pinyin":"duì",
        "englishTranslation":null,
        "spanishTranslation":"correcto, exacto",
        "example":""
    },
    {
        "word":"恐怕",
        "pinyin":"kǒngpà",
        "englishTranslation":null,
        "spanishTranslation":"quizás, temer que",
        "example":""
    },
    {
        "word":"抱歉",
        "pinyin":"bàoqiàn",
        "englishTranslation":null,
        "spanishTranslation":"lo siento",
        "example":""
    },
    {
        "word":"抱",
        "pinyin":"bào",
        "englishTranslation":null,
        "spanishTranslation":"abrazar",
        "example":""
    },
    {
        "word":"歉",
        "pinyin":"qiàn",
        "englishTranslation":null,
        "spanishTranslation":"mala cosecha, culpa",
        "example":""
    },
    {
        "word":"时间",
        "pinyin":"shíjiān",
        "englishTranslation":null,
        "spanishTranslation":"tiempo",
        "example":"你星期日有没有时间?"
    },
    {
        "word":"星巴克",
        "pinyin":"xīngbākè",
        "englishTranslation":null,
        "spanishTranslation":"Starbucks",
        "example":""
    },
    {
        "word":"游泳",
        "pinyin":"yóuyǒng",
        "englishTranslation":null,
        "spanishTranslation":"nadar",
        "example":""
    },
    {
        "word":"巧克力",
        "pinyin":"qiǎokèlì",
        "englishTranslation":null,
        "spanishTranslation":"chocolate",
        "example":""
    },
    {
        "word":"有意思",
        "pinyin":"yǒuyìsi",
        "englishTranslation":null,
        "spanishTranslation":"interesante",
        "example":""
    },
    {
        "word":"意思",
        "pinyin":"yìsi",
        "englishTranslation":null,
        "spanishTranslation":"significar, significado",
        "example":"这什么意思? 这是什么意思?"
    },
    {
        "word":"糖",
        "pinyin":"táng",
        "englishTranslation":null,
        "spanishTranslation":"azúcar",
        "example":""
    },
    {
        "word":"遍",
        "pinyin":"biàn",
        "englishTranslation":null,
        "spanishTranslation":"número de veces (de una acción), casi sinónimo de 次",
        "example":"再一遍"
    },
    {
        "word":"英国",
        "pinyin":"yīngguó",
        "englishTranslation":null,
        "spanishTranslation":"Inglaterra, Gran Bretaña",
        "example":""
    },
    {
        "word":"德国",
        "pinyin":"déguó",
        "englishTranslation":null,
        "spanishTranslation":"Alemania",
        "example":""
    },
    {
        "word":"德",
        "pinyin":"dé",
        "englishTranslation":null,
        "spanishTranslation":"virtud",
        "example":""
    },
    {
        "word":"给",
        "pinyin":"gěi",
        "englishTranslation":null,
        "spanishTranslation":"dar",
        "example":"请给我_______"
    },
    {
        "word":"进来",
        "pinyin":"jìnlai",
        "englishTranslation":null,
        "spanishTranslation":"entrar",
        "example":""
    },
    {
        "word":"进",
        "pinyin":"jìn",
        "englishTranslation":null,
        "spanishTranslation":"ingresar, entrar",
        "example":"进口、请进、进来、进去"
    },
    {
        "word":"来",
        "pinyin":"lái",
        "englishTranslation":null,
        "spanishTranslation":"venir",
        "example":"请进来。可以进来吗?"
    },
    {
        "word":"坐",
        "pinyin":"zuò",
        "englishTranslation":null,
        "spanishTranslation":"sentarse",
        "example":"请坐"
    },
    {
        "word":"巴西",
        "pinyin":"bāxī",
        "englishTranslation":null,
        "spanishTranslation":"Brasil",
        "example":"巴西人、巴西咖啡"
    },
    {
        "word":"但是",
        "pinyin":"dànshì",
        "englishTranslation":null,
        "spanishTranslation":"pero = 可是",
        "example":""
    },
    {
        "word":"那么",
        "pinyin":"nàme",
        "englishTranslation":null,
        "spanishTranslation":"entonces",
        "example":""
    },
    {
        "word":"杯子",
        "pinyin":"bēizi",
        "englishTranslation":null,
        "spanishTranslation":"vaso, taza, copa",
        "example":"一个杯子。一杯咖啡、一杯茶、三杯水、四杯果汁、五杯啤酒…"
    },
    {
        "word":"马上",
        "pinyin":"mǎshàng",
        "englishTranslation":null,
        "spanishTranslation":"enseguida",
        "example":"马上来"
    },
    {
        "word":"去",
        "pinyin":"qù",
        "englishTranslation":null,
        "spanishTranslation":"ir",
        "example":"去餐厅、去咖啡厅、去医院、去法院、去西班牙餐厅、去意大利咖啡厅、去英国医院、去医学院、去法学院、去语言学院、去医学中心"
    },
    {
        "word":"意大利",
        "pinyin":"yìdàlì",
        "englishTranslation":null,
        "spanishTranslation":"Italia",
        "example":""
    },
    {
        "word":"学院",
        "pinyin":"xuéyuàn",
        "englishTranslation":null,
        "spanishTranslation":"instituto, universidad, escuela",
        "example":""
    },
    {
        "word":"医院",
        "pinyin":"yīyuàn",
        "englishTranslation":null,
        "spanishTranslation":"hospital",
        "example":""
    },
    {
        "word":"层",
        "pinyin":"céng",
        "englishTranslation":"floor",
        "spanishTranslation":"piso, planta",
        "example":""
    },
    {
        "word":"餐厅",
        "pinyin":"cāntīng",
        "englishTranslation":null,
        "spanishTranslation":"restaurante",
        "example":"中国餐厅、法国餐厅、西班牙餐厅"
    },
    {
        "word":"餐",
        "pinyin":"cān",
        "englishTranslation":"meal",
        "spanishTranslation":"comida",
        "example":"早餐、中餐/午餐、晚餐、西餐…"
    },
    {
        "word":"吃早餐",
        "pinyin":"chīzǎocān",
        "englishTranslation":null,
        "spanishTranslation":"desayunar",
        "example":""
    },
    {
        "word":"吃中餐",
        "pinyin":"chīzhōngcān",
        "englishTranslation":null,
        "spanishTranslation":"almorzar",
        "example":""
    },
    {
        "word":"吃午餐",
        "pinyin":"chīwǔcān",
        "englishTranslation":null,
        "spanishTranslation":"almorzar",
        "example":""
    },
    {
        "word":"中午",
        "pinyin":"zhōngwǔ",
        "englishTranslation":null,
        "spanishTranslation":"mediodía",
        "example":""
    },
    {
        "word":"吃晚餐",
        "pinyin":"chīwǎncān",
        "englishTranslation":null,
        "spanishTranslation":"cenar",
        "example":""
    },
    {
        "word":"哪儿",
        "pinyin":"nǎr",
        "englishTranslation":null,
        "spanishTranslation":"¿dónde? = 哪里",
        "example":""
    },
    {
        "word":"那儿",
        "pinyin":"nàr",
        "englishTranslation":null,
        "spanishTranslation":"ahí, allí, allá = 那里",
        "example":""
    },
    {
        "word":"请问",
        "pinyin":"qǐngwèn",
        "englishTranslation":null,
        "spanishTranslation":"¿Podría preguntarle...?",
        "example":""
    },
    {
        "word":"请",
        "pinyin":"qǐng",
        "englishTranslation":null,
        "spanishTranslation":"por favor",
        "example":"请问、请喝、请吃、请工作、请你们学习…"
    },
    {
        "word":"问",
        "pinyin":"wèn",
        "englishTranslation":null,
        "spanishTranslation":"preguntar",
        "example":"问老师，问朋友"
    },
    {
        "word":"厅",
        "pinyin":"tīng",
        "englishTranslation":null,
        "spanishTranslation":"sala, salón",
        "example":"咖啡厅"
    },
    {
        "word":"在",
        "pinyin":"zài",
        "englishTranslation":null,
        "spanishTranslation":"en, estar",
        "example":"我在咖啡厅"
    },
    {
        "word":"哪里",
        "pinyin":"nǎlǐ",
        "englishTranslation":null,
        "spanishTranslation":"¿dónde?",
        "example":""
    },
    {
        "word":"没关系",
        "pinyin":"méi guānxì",
        "englishTranslation":null,
        "spanishTranslation":"no importa, no pasa nada, todo bien",
        "example":""
    },
    {
        "word":"那里",
        "pinyin":"nàlǐ",
        "englishTranslation":null,
        "spanishTranslation":"ahí, allí, allá",
        "example":""
    },
    {
        "word":"不客气",
        "pinyin":"bù kèqì",
        "englishTranslation":null,
        "spanishTranslation":"de nada",
        "example":""
    },
    {
        "word":"不用",
        "pinyin":"búyòng",
        "englishTranslation":null,
        "spanishTranslation":"no necesitar",
        "example":""
    },
    {
        "word":"先生",
        "pinyin":"xiānshēng",
        "englishTranslation":null,
        "spanishTranslation":"señor, esposo, marido",
        "example":""
    },
    {
        "word":"小姐",
        "pinyin":"xiǎojiě",
        "englishTranslation":null,
        "spanishTranslation":"señorita",
        "example":""
    },
    {
        "word":"太太",
        "pinyin":"tàitai",
        "englishTranslation":null,
        "spanishTranslation":"señora, esposa",
        "example":""
    },
    {
        "word":"贵",
        "pinyin":"guì",
        "englishTranslation":null,
        "spanishTranslation":"caro/a, noble, honorable",
        "example":""
    },
    {
        "word":"陈",
        "pinyin":"chén",
        "englishTranslation":null,
        "spanishTranslation":"un apellido",
        "example":""
    },
    {
        "word":"法国",
        "pinyin":"fǎguó",
        "englishTranslation":null,
        "spanishTranslation":"Francia",
        "example":""
    },
    {
        "word":"法",
        "pinyin":"fǎ",
        "englishTranslation":null,
        "spanishTranslation":"ley",
        "example":""
    },
    {
        "word":"太...了",
        "pinyin":"tài...le",
        "englishTranslation":null,
        "spanishTranslation":"expresión exclamativa",
        "example":"太好了，太忙了，太红了，太贵了，太美了"
    },
    {
        "word":"语言",
        "pinyin":"yǔyán",
        "englishTranslation":null,
        "spanishTranslation":"idioma, lengua",
        "example":"你说什么语言?"
    },
    {
        "word":"西班牙",
        "pinyin":"xībānyá",
        "englishTranslation":null,
        "spanishTranslation":"España",
        "example":""
    },
    {
        "word":"西班牙语",
        "pinyin":"xībānyáyǔ",
        "englishTranslation":null,
        "spanishTranslation":"idioma español",
        "example":""
    },
    {
        "word":"西班牙文",
        "pinyin":"xībānyáwén",
        "englishTranslation":null,
        "spanishTranslation":"idioma español",
        "example":""
    },
    {
        "word":"果汁",
        "pinyin":"guǒzhī",
        "englishTranslation":null,
        "spanishTranslation":"jugo",
        "example":""
    },
    {
        "word":"果",
        "pinyin":"guǒ",
        "englishTranslation":null,
        "spanishTranslation":"fruto",
        "example":""
    },
    {
        "word":"汁",
        "pinyin":"zhī",
        "englishTranslation":null,
        "spanishTranslation":"jugo",
        "example":""
    },
    {
        "word":"三明治",
        "pinyin":"sānmíngzhì",
        "englishTranslation":null,
        "spanishTranslation":"sándwich",
        "example":""
    },
    {
        "word":"做",
        "pinyin":"zuò",
        "englishTranslation":null,
        "spanishTranslation":"hacer",
        "example":"你做什么工作?"
    },
    {
        "word":"医生",
        "pinyin":"yīshēng",
        "englishTranslation":null,
        "spanishTranslation":"médico/a",
        "example":""
    },
    {
        "word":"记者",
        "pinyin":"jìzhě",
        "englishTranslation":null,
        "spanishTranslation":"periodista",
        "example":""
    },
    {
        "word":"汽水",
        "pinyin":"qìshuǐ",
        "englishTranslation":null,
        "spanishTranslation":"gaseosa",
        "example":""
    },
    {
        "word":"汽",
        "pinyin":"qì",
        "englishTranslation":null,
        "spanishTranslation":"gas, vapor",
        "example":""
    },
    {
        "word":"汉语",
        "pinyin":"hànyǔ",
        "englishTranslation":null,
        "spanishTranslation":"idioma chino",
        "example":""
    },
    {
        "word":"语",
        "pinyin":"yǔ",
        "englishTranslation":null,
        "spanishTranslation":"lengua, idioma",
        "example":""
    },
    {
        "word":"外语",
        "pinyin":"wàiyǔ",
        "englishTranslation":null,
        "spanishTranslation":"lengua extranjera",
        "example":""
    },
    {
        "word":"说",
        "pinyin":"shuō",
        "englishTranslation":null,
        "spanishTranslation":"hablar",
        "example":""
    },
    {
        "word":"英语",
        "pinyin":"yīngyǔ",
        "englishTranslation":null,
        "spanishTranslation":"idioma inglés",
        "example":""
    },
    {
        "word":"当然",
        "pinyin":"dāngrán",
        "englishTranslation":null,
        "spanishTranslation":"por supuesto, obvio",
        "example":""
    },
    {
        "word":"美国",
        "pinyin":"měiguó",
        "englishTranslation":null,
        "spanishTranslation":"Estados Unidos",
        "example":""
    },
    {
        "word":"美",
        "pinyin":"měi",
        "englishTranslation":null,
        "spanishTranslation":"hermosura, belleza",
        "example":""
    },
    {
        "word":"吃",
        "pinyin":"chī",
        "englishTranslation":null,
        "spanishTranslation":"comer",
        "example":""
    },
    {
        "word":"面包",
        "pinyin":"miànbāo",
        "englishTranslation":null,
        "spanishTranslation":"pan",
        "example":""
    },
    {
        "word":"啤酒",
        "pinyin":"píjiǔ",
        "englishTranslation":null,
        "spanishTranslation":"cerveza",
        "example":""
    },
    {
        "word":"太",
        "pinyin":"tài",
        "englishTranslation":null,
        "spanishTranslation":"demasiado",
        "example":""
    },
    {
        "word":"阿根廷",
        "pinyin":"āgēntíng",
        "englishTranslation":"Argentina",
        "spanishTranslation":"Argentina",
        "example":""
    },
    {
        "word":"中国",
        "pinyin":"zhōngguó",
        "englishTranslation":"China",
        "spanishTranslation":"China",
        "example":""
    },
    {
        "word":"老师",
        "pinyin":"lǎoshī",
        "englishTranslation":null,
        "spanishTranslation":"profesor",
        "example":""
    },
    {
        "word":"那",
        "pinyin":"nà",
        "englishTranslation":null,
        "spanishTranslation":"ése/a, aquél, aquélla",
        "example":""
    },
    {
        "word":"人",
        "pinyin":"rén",
        "englishTranslation":null,
        "spanishTranslation":"gente, persona",
        "example":""
    },
    {
        "word":"哪",
        "pinyin":"nǎ",
        "englishTranslation":null,
        "spanishTranslation":"¿cuál? ¿de qué?",
        "example":""
    },
    {
        "word":"英国",
        "pinyin":"yīngguó",
        "englishTranslation":null,
        "spanishTranslation":"Inglaterra",
        "example":""
    },
    {
        "word":"国",
        "pinyin":"guó",
        "englishTranslation":"country",
        "spanishTranslation":"país, nación",
        "example":""
    },
    {
        "word":"红茶",
        "pinyin":"hóngchá",
        "englishTranslation":null,
        "spanishTranslation":"té negro",
        "example":""
    },
    {
        "word":"加拿大",
        "pinyin":"jiānádà",
        "englishTranslation":null,
        "spanishTranslation":"Canadá",
        "example":""
    },
    {
        "word":"加",
        "pinyin":"jiā",
        "englishTranslation":null,
        "spanishTranslation":"sumar, agregar",
        "example":""
    },
    {
        "word":"牛奶",
        "pinyin":"niúnǎi",
        "englishTranslation":null,
        "spanishTranslation":"leche de vaca",
        "example":""
    },
    {
        "word":"牛",
        "pinyin":"niú",
        "englishTranslation":null,
        "spanishTranslation":"Bovinae",
        "example":""
    },
    {
        "word":"奶",
        "pinyin":"nǎi",
        "englishTranslation":null,
        "spanishTranslation":"leche",
        "example":""
    },
    {
        "word":"喜欢",
        "pinyin":"xǐhuān",
        "englishTranslation":null,
        "spanishTranslation":"gustar, preferir",
        "example":""
    },
    {
        "word":"红酒",
        "pinyin":"hóngjiǔ",
        "englishTranslation":null,
        "spanishTranslation":"vino tinto",
        "example":""
    },
    {
        "word":"红",
        "pinyin":"hóng",
        "englishTranslation":null,
        "spanishTranslation":"rojo/a",
        "example":""
    },
    {
        "word":"中文",
        "pinyin":"zhōngwén",
        "englishTranslation":null,
        "spanishTranslation":"idioma chino",
        "example":"中文名字，中文名片"
    },
    {
        "word":"中",
        "pinyin":"zhōng",
        "englishTranslation":null,
        "spanishTranslation":"centro, medio",
        "example":""
    },
    {
        "word":"文",
        "pinyin":"wén",
        "englishTranslation":null,
        "spanishTranslation":"escritura, letra",
        "example":""
    },
    {
        "word":"水",
        "pinyin":"shuǐ",
        "englishTranslation":null,
        "spanishTranslation":"agua",
        "example":""
    },
    {
        "word":"可乐",
        "pinyin":"kělè",
        "englishTranslation":null,
        "spanishTranslation":"cola",
        "example":""
    },
    {
        "word":"乐",
        "pinyin":"lè",
        "englishTranslation":null,
        "spanishTranslation":"feliz, jubiloso/a",
        "example":""
    },
    {
        "word":"有",
        "pinyin":"yǒu",
        "englishTranslation":null,
        "spanishTranslation":"tener, haber",
        "example":""
    },
    {
        "word":"没有",
        "pinyin":"méiyǒu",
        "englishTranslation":null,
        "spanishTranslation":"no tener",
        "example":""
    },
    {
        "word":"对不起",
        "pinyin":"duìbùqǐ",
        "englishTranslation":null,
        "spanishTranslation":"perdón, disculpe, lo siento",
        "example":""
    },
    {
        "word":"酒",
        "pinyin":"jiǔ",
        "englishTranslation":null,
        "spanishTranslation":"bebida alcohólica",
        "example":""
    },
    {
        "word":"茶",
        "pinyin":"chá",
        "englishTranslation":null,
        "spanishTranslation":"té",
        "example":""
    },
    {
        "word":"要",
        "pinyin":"yào",
        "englishTranslation":"to want",
        "spanishTranslation":"querer",
        "example":""
    },
    {
        "word":"喝",
        "pinyin":"hē",
        "englishTranslation":"to drink",
        "spanishTranslation":"tomar, beber",
        "example":""
    },
    {
        "word":"咖啡",
        "pinyin":"kāfēi",
        "englishTranslation":"coffee",
        "spanishTranslation":"café",
        "example":""
    },
    {
        "word":"都",
        "pinyin":"dōu",
        "englishTranslation":"all, both",
        "spanishTranslation":"todo, ambos",
        "example":""
    },
    {
        "word":"知道",
        "pinyin":"zhīdào",
        "englishTranslation":"to know",
        "spanishTranslation":"saber, enterarse",
        "example":""
    },
    {
        "word":"奶奶",
        "pinyin":"nǎinai",
        "englishTranslation":"paternal grandmother",
        "spanishTranslation":"abuela paterna",
        "example":""
    },
    
    {
        "word":"外婆",
        "pinyin":"wàipó",
        "englishTranslation":"maternal grandmother",
        "spanishTranslation":"abuela materna",
        "example":""
    },
    {
        "word":"哥哥",
        "pinyin":"gēge",
        "englishTranslation":"older brother",
        "spanishTranslation":"hermano mayor",
        "example":""
    },
    {
        "word":"弟弟",
        "pinyin":"dìdi",
        "englishTranslation":"younger brother",
        "spanishTranslation":"hermano menor",
        "example":""
    },
    {
        "word":"姐姐",
        "pinyin":"jiějie",
        "englishTranslation":null,
        "spanishTranslation":"hermana mayor",
        "example":""
    },
    {
        "word":"妹妹",
        "pinyin":"mèimei",
        "englishTranslation":null,
        "spanishTranslation":"hermana menor",
        "example":""
    },
    {
        "word":"名字",
        "pinyin":"míngzi",
        "englishTranslation":null,
        "spanishTranslation":"nombre",
        "example":"你的名字，叫什么名字"
    },
    {
        "word":"介绍",
        "pinyin":"jièshào",
        "englishTranslation":null,
        "spanishTranslation":"presentar",
        "example":"介绍林娜，介绍语言学院"
    },
    {
        "word":"谁",
        "pinyin":"shéi",
        "englishTranslation":null,
        "spanishTranslation":"¿quién?",
        "example":""
    },
    {
        "word":"妈妈",
        "pinyin":"māma",
        "englishTranslation":"mother",
        "spanishTranslation":"madre",
        "example":""
    },
    {
        "word":"教授",
        "pinyin":"jiàoshòu",
        "englishTranslation":"",
        "spanishTranslation":"profesor universitario",
        "example":""
    },
    {
        "word":"教",
        "pinyin":"jiào",
        "englishTranslation":"",
        "spanishTranslation":"enseñar, impartir clase",
        "example":""
    },
    {
        "word":"名片",
        "pinyin":"míngpiàn",
        "englishTranslation":"",
        "spanishTranslation":"tarjeta de visita",
        "example":"我的名片，老师的名片"
    },
    {
        "word":"叫",
        "pinyin":"jiào",
        "englishTranslation":"to be called",
        "spanishTranslation":"llamarse",
        "example":""
    },
    {
        "word":"贵姓",
        "pinyin":"guìxìng",
        "englishTranslation":null,
        "spanishTranslation":"¿Cómo se apellida?",
        "example":""
    },
    {
        "word":"贵",
        "pinyin":"guì",
        "englishTranslation":null,
        "spanishTranslation":"caro/a, noble, honorable",
        "example":"您贵姓? 我姓________。"
    },
    {
        "word":"这儿",
        "pinyin":"zhèr",
        "englishTranslation":"here",
        "spanishTranslation":"aquí",
        "example":""
    },
    {
        "word":"这",
        "pinyin":"zhè",
        "englishTranslation":null,
        "spanishTranslation":"éste/a, esto",
        "example":""
    },
    {
        "word":"爸爸",
        "pinyin":"bàba",
        "englishTranslation":"father",
        "spanishTranslation":"padre",
        "example":""
    },
    {
        "word":"看",
        "pinyin":"kàn",
        "englishTranslation":null,
        "spanishTranslation":"mirar, ver",
        "example":"看老师，看这儿"
    },
    {
        "word":"高兴",
        "pinyin":"gāoxìng",
        "englishTranslation":null,
        "spanishTranslation":"contento/a",
        "example":""
    },
    {
        "word":"认识",
        "pinyin":"rènshi",
        "englishTranslation":null,
        "spanishTranslation":"conocer",
        "example":""
    },
    {
        "word":"很高兴认识你",
        "pinyin":"hěngāoxìngrènshinǐ",
        "englishTranslation":null,
        "spanishTranslation":"mucho gusto",
        "example":""
    },
    {
        "word":"认识你很高兴",
        "pinyin":"rènshinǐhěngāoxìng",
        "englishTranslation":null,
        "spanishTranslation":"mucho gusto",
        "example":""
    },
    {
        "word":"高",
        "pinyin":"gāo",
        "englishTranslation":null,
        "spanishTranslation":"alto",
        "example":""
    },
    {
        "word":"文化",
        "pinyin":"wénhuà",
        "englishTranslation":null,
        "spanishTranslation":"cultura",
        "example":""
    },
    {
        "word":"历史",
        "pinyin":"lìshǐ",
        "englishTranslation":null,
        "spanishTranslation":"historia",
        "example":""
    },
    {
        "word":"哲学",
        "pinyin":"zhéxué",
        "englishTranslation":null,
        "spanishTranslation":"filosofía",
        "example":""
    },
    {
        "word":"音乐",
        "pinyin":"yīnyuè",
        "englishTranslation":null,
        "spanishTranslation":"música",
        "example":""
    },
    {
        "word":"经济",
        "pinyin":"jīngjì",
        "englishTranslation":null,
        "spanishTranslation":"economía",
        "example":""
    },
    {
        "word":"数学",
        "pinyin":"shùxué",
        "englishTranslation":null,
        "spanishTranslation":"matemáticas",
        "example":""
    },
    {
        "word":"物理",
        "pinyin":"wùlǐ",
        "englishTranslation":null,
        "spanishTranslation":"física",
        "example":""
    },
    {
        "word":"化学",
        "pinyin":"huàxué",
        "englishTranslation":null,
        "spanishTranslation":"química",
        "example":""
    },
    {
        "word":"教育",
        "pinyin":"jiàoyù",
        "englishTranslation":null,
        "spanishTranslation":"educación",
        "example":""
    },
    {
        "word":"选修",
        "pinyin":"xuǎnxiū",
        "englishTranslation":null,
        "spanishTranslation":"escoger una asignatura optativa",
        "example":""
    },
    {
        "word":"专业",
        "pinyin":"zhuānyè",
        "englishTranslation":null,
        "spanishTranslation":"carrera, especialidad",
        "example":"中文专业，汉语专业，语言专业"
    },
    {
        "word":"美术",
        "pinyin":"měishù",
        "englishTranslation":null,
        "spanishTranslation":"bellas artes",
        "example":"学习美术，美术专业"
    },
    {
        "word":"文学",
        "pinyin":"wénxué",
        "englishTranslation":null,
        "spanishTranslation":"literatura",
        "example":"中国文学，文学专业"
    },
    {
        "word":"系",
        "pinyin":"xì",
        "englishTranslation":null,
        "spanishTranslation":"facultad, departamento",
        "example":"汉语系，语言系，中文系"
    },
    {
        "word":"开",
        "pinyin":"kāi",
        "englishTranslation":null,
        "spanishTranslation":"empezar",
        "example":""
    },
    {
        "word":"开学",
        "pinyin":"kāixué",
        "englishTranslation":null,
        "spanishTranslation":"empezar el colegio",
        "example":""
    },
    {
        "word":"学生",
        "pinyin":"xuésheng",
        "englishTranslation":null,
        "spanishTranslation":"estudiante",
        "example":""
    },
    {
        "word":"学习",
        "pinyin":"xuéxí",
        "englishTranslation":null,
        "spanishTranslation":"estudiar, aprender",
        "example":""
    },
    {
        "word":"学",
        "pinyin":"xué",
        "englishTranslation":null,
        "spanishTranslation":"estudiar, aprender",
        "example":"学中文，学汉语"
    },
    {
        "word":"身体",
        "pinyin":"shēntǐ",
        "englishTranslation":null,
        "spanishTranslation":"cuerpo, salud",
        "example":""
    },
    {
        "word":"工作",
        "pinyin":"gōngzuò",
        "englishTranslation":null,
        "spanishTranslation":"trabajo, trabajar",
        "example":""
    },
    {
        "word":"宿舍",
        "pinyin":"sùshè",
        "englishTranslation":null,
        "spanishTranslation":"dormitorio",
        "example":""
    },
    {
        "word":"一下",
        "pinyin":"yíxià",
        "englishTranslation":null,
        "spanishTranslation":"se utiliza después de un verbo para indicar una acción rápida",
        "example":"认识一下，问一下，看一下"
    },
    {
        "word":"次",
        "pinyin":"cì",
        "englishTranslation":null,
        "spanishTranslation":"vez",
        "example":""
    },
    {
        "word":"下次",
        "pinyin":"xiàcì",
        "englishTranslation":null,
        "spanishTranslation":"la próxima vez",
        "example":""
    },
    {
        "word":"再一次",
        "pinyin":"zàiyīcì",
        "englishTranslation":null,
        "spanishTranslation":"otra vez",
        "example":""
    },
    {
        "word":"再",
        "pinyin":"zài",
        "englishTranslation":null,
        "spanishTranslation":"otra vez",
        "example":""
    },
    {
        "word":"再见",
        "pinyin":"zàijiàn",
        "englishTranslation":null,
        "spanishTranslation":"¡Hasta luego!",
        "example":""
    },
    {
        "word":"忙",
        "pinyin":"máng",
        "englishTranslation":"busy",
        "spanishTranslation":"ocupado/a",
        "example":""
    },
    {
        "word":"天气",
        "pinyin":"tiānqì",
        "englishTranslation":null,
        "spanishTranslation":"tiempo, clima",
        "example":""
    },
    {
        "word":"气",
        "pinyin":"qì",
        "englishTranslation":null,
        "spanishTranslation":"aire, energía",
        "example":""
    },
    {
        "word":"男朋友",
        "pinyin":"nánpéngyǒu",
        "englishTranslation":"boyfriend",
        "spanishTranslation":"novio",
        "example":""
    },
    {
        "word":"女朋友",
        "pinyin":"nǚpéngyǒu",
        "englishTranslation":"girlfriend",
        "spanishTranslation":"novia",
        "example":""
    },
    {
        "word":"女",
        "pinyin":"nǚ",
        "englishTranslation":"woman, female",
        "spanishTranslation":"mujer",
        "example":""
    },
    {
        "word":"男",
        "pinyin":"nán",
        "englishTranslation":"man, male",
        "spanishTranslation":"varón, hombre",
        "example":""
    },
    {
        "word":"朋友",
        "pinyin":"péngyǒu",
        "englishTranslation":null,
        "spanishTranslation":"amigo/a",
        "example":""
    },
    {
        "word":"年",
        "pinyin":"nián",
        "englishTranslation":null,
        "spanishTranslation":"año",
        "example":""
    },
    {
        "word":"零",
        "pinyin":"líng",
        "englishTranslation":null,
        "spanishTranslation":"cero",
        "example":""
    },
    {
        "word":"〇",
        "pinyin":"líng",
        "englishTranslation":null,
        "spanishTranslation":"cero",
        "example":""
    },
    {
        "word":"京剧",
        "pinyin":"jīngjù",
        "englishTranslation":null,
        "spanishTranslation":"Ópera de Pekín",
        "example":""
    },
    {
        "word":"怎么样",
        "pinyin":"zěnmeyàng",
        "englishTranslation":null,
        "spanishTranslation":"¿qué tal?",
        "example":""
    },
    {
        "word":"怎么",
        "pinyin":"zěnme",
        "englishTranslation":null,
        "spanishTranslation":"¿cómo?",
        "example":""
    },
    {
        "word":"样",
        "pinyin":"yàng",
        "englishTranslation":null,
        "spanishTranslation":"forma, manera",
        "example":""
    },
    {
        "word":"昨天",
        "pinyin":"zuótiān",
        "englishTranslation":null,
        "spanishTranslation":"ayer",
        "example":""
    },
    {
        "word":"姓",
        "pinyin":"xìng",
        "englishTranslation":null,
        "spanishTranslation":"apellido, apellidarse",
        "example":""
    },
    {
        "word":"王",
        "pinyin":"wáng",
        "englishTranslation":null,
        "spanishTranslation":"rey",
        "example":""
    },
    {
        "word":"我们",
        "pinyin":"wǒmen",
        "englishTranslation":"we",
        "spanishTranslation":"nosotros",
        "example":""
    },
    {
        "word":"你们",
        "pinyin":"nǐmen",
        "englishTranslation":"you (plural)",
        "spanishTranslation":"ustedes",
        "example":""
    },
    {
        "word":"他们",
        "pinyin":"tāmen",
        "englishTranslation":"they",
        "spanishTranslation":"ellos",
        "example":""
    },
    {
        "word":"她们",
        "pinyin":"tāmen",
        "englishTranslation":"they",
        "spanishTranslation":"ellas",
        "example":""
    },
    {
        "word":"他",
        "pinyin":"tā",
        "englishTranslation":null,
        "spanishTranslation":"él",
        "example":""
    },
    {
        "word":"她",
        "pinyin":"tā",
        "englishTranslation":null,
        "spanishTranslation":"ella",
        "example":""
    },
    {
        "word":"几",
        "pinyin":"jǐ",
        "englishTranslation":null,
        "spanishTranslation":"cuántos",
        "example":""
    },
    {
        "word":"几月",
        "pinyin":"jǐyuè",
        "englishTranslation":null,
        "spanishTranslation":"¿qué mes?",
        "example":""
    },
    {
        "word":"几号",
        "pinyin":"jǐhào",
        "englishTranslation":null,
        "spanishTranslation":"¿qué día?",
        "example":""
    },
    {
        "word":"几月几号",
        "pinyin":"jǐyuèjǐhào",
        "englishTranslation":null,
        "spanishTranslation":"¿qué fecha?",
        "example":""
    },
    {
        "word":"星期几",
        "pinyin":"xīngqījǐ",
        "englishTranslation":null,
        "spanishTranslation":"¿qué día de la semana?",
        "example":""
    },
    {
        "word":"星期",
        "pinyin":"xīngqī",
        "englishTranslation":null,
        "spanishTranslation":"semana",
        "example":""
    },
    {
        "word":"星",
        "pinyin":"xīng",
        "englishTranslation":null,
        "spanishTranslation":"estrella",
        "example":""
    },
    {
        "word":"期",
        "pinyin":"qī",
        "englishTranslation":null,
        "spanishTranslation":"periódo",
        "example":""
    },
    {
        "word":"星期一",
        "pinyin":"xīngqīyī",
        "englishTranslation":"Monday",
        "spanishTranslation":"lunes",
        "example":""
    },
    {
        "word":"星期二",
        "pinyin":"xīngqīèr",
        "englishTranslation":"Tuesday",
        "spanishTranslation":"martes",
        "example":""
    },
    {
        "word":"星期三",
        "pinyin":"xīngqīsān",
        "englishTranslation":"Wednesday",
        "spanishTranslation":"miércoles",
        "example":""
    },
    {
        "word":"星期四",
        "pinyin":"xīngqīsì",
        "englishTranslation":"Thursday",
        "spanishTranslation":"jueves",
        "example":""
    },
    {
        "word":"星期五",
        "pinyin":"xīngqīwǔ",
        "englishTranslation":"Friday",
        "spanishTranslation":"viernes",
        "example":""
    },
    {
        "word":"星期六",
        "pinyin":"xīngqīliù",
        "englishTranslation":"Saturday",
        "spanishTranslation":"sábado",
        "example":""
    },
    {
        "word":"星期日",
        "pinyin":"xīngqīrì",
        "englishTranslation":"Sunday",
        "spanishTranslation":"domingo",
        "example":""
    },
    {
        "word":"星期天",
        "pinyin":"xīngqītiān",
        "englishTranslation":"Sunday",
        "spanishTranslation":"domingo",
        "example":""
    },
    {
        "word":"今天",
        "pinyin":"jīntiān",
        "englishTranslation":null,
        "spanishTranslation":"hoy",
        "example":""
    },
    {
        "word":"今",
        "pinyin":"jīn",
        "englishTranslation":null,
        "spanishTranslation":"este, presente",
        "example":""
    },
    {
        "word":"们",
        "pinyin":"men",
        "englishTranslation":"plural",
        "spanishTranslation":"plural",
        "example":""
    },
    {
        "word":"好不好",
        "pinyin":"hǎobùhǎo",
        "englishTranslation":null,
        "spanishTranslation":"una forma afirmativa-negativa de formular preguntas, equivale a 好吗",
        "example":""
    },
    {
        "word":"还可以",
        "pinyin":"háikěyǐ",
        "englishTranslation":null,
        "spanishTranslation":"aceptable",
        "example":""
    },
    {
        "word":"还",
        "pinyin":"hái",
        "englishTranslation":null,
        "spanishTranslation":"todavía",
        "example":""
    },
    {
        "word":"可以",
        "pinyin":"kěyǐ",
        "englishTranslation":null,
        "spanishTranslation":"poder",
        "example":""
    },
    {
        "word":"号",
        "pinyin":"hào",
        "englishTranslation":null,
        "spanishTranslation":"número, se usa en la fecha como el día",
        "example":"四月二十二日 = 四月二十二号"
    },
    {
        "word":"马马虎虎",
        "pinyin":"mǎmǎhūhū",
        "englishTranslation":null,
        "spanishTranslation":"más o menos",
        "example":""
    },
    {
        "word":"虎",
        "pinyin":"hǔ",
        "englishTranslation":null,
        "spanishTranslation":"tigre",
        "example":""
    },
    {
        "word":"马",
        "pinyin":"mǎ",
        "englishTranslation":null,
        "spanishTranslation":"caballo",
        "example":""
    },
    {
        "word":"明天见",
        "pinyin":"míngtiānjiàn",
        "englishTranslation":null,
        "spanishTranslation":"hasta mañana",
        "example":""
    },
    {
        "word":"明天",
        "pinyin":"míngtiān",
        "englishTranslation":null,
        "spanishTranslation":"mañana",
        "example":""
    },
    {
        "word":"明",
        "pinyin":"míng",
        "englishTranslation":null,
        "spanishTranslation":"brillante",
        "example":""
    },
    {
        "word":"天",
        "pinyin":"tiān",
        "englishTranslation":null,
        "spanishTranslation":"cielo, día",
        "example":""
    },
    {
        "word":"是",
        "pinyin":"shì",
        "englishTranslation":"to be",
        "spanishTranslation":"ser",
        "example":""
    },
    {
        "word":"我是",
        "pinyin":"wǒshì",
        "englishTranslation":null,
        "spanishTranslation":"yo soy",
        "example":""
    },
    {
        "word":"不错",
        "pinyin":"bùcuò",
        "englishTranslation":null,
        "spanishTranslation":"no mal, bien",
        "example":""
    },
    {
        "word":"不",
        "pinyin":"bù",
        "englishTranslation":"no",
        "spanishTranslation":"no",
        "example":""
    },
    {
        "word":"错",
        "pinyin":"cuò",
        "englishTranslation":null,
        "spanishTranslation":"mal, error, equivocación",
        "example":""
    },
    {
        "word":"的",
        "pinyin":"de",
        "englishTranslation":null,
        "spanishTranslation":"posesivo",
        "example":""
    },
    {
        "word":"我的",
        "pinyin":"wǒde",
        "englishTranslation":null,
        "spanishTranslation":"mi, mío/a",
        "example":""
    },
    {
        "word":"早上好",
        "pinyin":"zǎoshànghǎo",
        "englishTranslation":null,
        "spanishTranslation":"buen día, buenos días",
        "example":""
    },
    {
        "word":"下午好",
        "pinyin":"xiàwǔhǎo",
        "englishTranslation":null,
        "spanishTranslation":"buenas tardes",
        "example":""
    },
    {
        "word":"晚上好",
        "pinyin":"wǎnshànghǎo",
        "englishTranslation":null,
        "spanishTranslation":"buenas noches",
        "example":""
    },
    {
        "word":"晚",
        "pinyin":"wǎn",
        "englishTranslation":null,
        "spanishTranslation":"tarde",
        "example":""
    },
    {
        "word":"早上",
        "pinyin":"zǎoshàng",
        "englishTranslation":null,
        "spanishTranslation":"la mañana",
        "example":""
    },
    {
        "word":"下午",
        "pinyin":"xiàwǔ",
        "englishTranslation":null,
        "spanishTranslation":"la tarde",
        "example":""
    },
    {
        "word":"晚上",
        "pinyin":"wǎnshàng",
        "englishTranslation":null,
        "spanishTranslation":"la noche",
        "example":""
    },
    {
        "word":"生日",
        "pinyin":"shēngrì",
        "englishTranslation":null,
        "spanishTranslation":"cumpleaños",
        "example":""
    },
    {
        "word":"生",
        "pinyin":"shēng",
        "englishTranslation":null,
        "spanishTranslation":"nacer, nacimiento",
        "example":""
    },
    {
        "word":"早",
        "pinyin":"zǎo",
        "englishTranslation":null,
        "spanishTranslation":"temprano",
        "example":""
    },
    {
        "word":"您",
        "pinyin":"nín",
        "englishTranslation":"you (formal)",
        "spanishTranslation":"usted",
        "example":""
    },
    {
        "word":"你呢",
        "pinyin":"nǐne",
        "englishTranslation":"and you?",
        "spanishTranslation":"¿y tú/vos?",
        "example":""
    },
    {
        "word":"呢",
        "pinyin":"ne",
        "englishTranslation":null,
        "spanishTranslation":"partícula modal para preguntas elípticas",
        "example":""
    },
    {
        "word":"也",
        "pinyin":"yě",
        "englishTranslation":"also",
        "spanishTranslation":"también, además",
        "example":""
    },
    {
        "word":"日",
        "pinyin":"rì",
        "englishTranslation":"day",
        "spanishTranslation":"sol, día",
        "example":""
    },
    {
        "word":"谢谢",
        "pinyin":"xièxie",
        "englishTranslation":"thank you",
        "spanishTranslation":"gracias",
        "example":""
    },
    {
        "word":"月",
        "pinyin":"yuè",
        "englishTranslation":"month",
        "spanishTranslation":"mes",
        "example":""
    },
    {
        "word":"一月",
        "pinyin":"yīyuè",
        "englishTranslation":"January",
        "spanishTranslation":"enero",
        "example":""
    },
    {
        "word":"二月",
        "pinyin":"èryuè",
        "englishTranslation":"February",
        "spanishTranslation":"febrero",
        "example":""
    },
    {
        "word":"三月",
        "pinyin":"sānyuè",
        "englishTranslation":"March",
        "spanishTranslation":"marzo",
        "example":""
    },
    {
        "word":"四月",
        "pinyin":"sìyuè",
        "englishTranslation":"April",
        "spanishTranslation":"abril",
        "example":""
    },
    {
        "word":"五月",
        "pinyin":"wǔyuè",
        "englishTranslation":"May",
        "spanishTranslation":"mayo",
        "example":""
    },
    {
        "word":"六月",
        "pinyin":"liùyuè",
        "englishTranslation":"June",
        "spanishTranslation":"junio",
        "example":""
    },
    {
        "word":"七月",
        "pinyin":"qīyuè",
        "englishTranslation":"July",
        "spanishTranslation":"julio",
        "example":""
    },
    {
        "word":"八月",
        "pinyin":"bāyuè",
        "englishTranslation":"August",
        "spanishTranslation":"agosto",
        "example":""
    },
    {
        "word":"九月",
        "pinyin":"jiǔyuè",
        "englishTranslation":"September",
        "spanishTranslation":"septiembre",
        "example":""
    },
    {
        "word":"十月",
        "pinyin":"shíyuè",
        "englishTranslation":"October",
        "spanishTranslation":"octubre",
        "example":""
    },
    {
        "word":"十一月",
        "pinyin":"shíyīyuè",
        "englishTranslation":"November",
        "spanishTranslation":"noviembre",
        "example":""
    },
    {
        "word":"十二月",
        "pinyin":"shíèryuè",
        "englishTranslation":"December",
        "spanishTranslation":"diciembre",
        "example":""
    },
    {
        "word":"你好吗",
        "pinyin":"nǐhǎoma",
        "englishTranslation":"How are you?",
        "spanishTranslation":"¿Cómo estás?",
        "example":""
    },
    {
        "word":"吗",
        "pinyin":"ma",
        "englishTranslation":"",
        "spanishTranslation":"partícula interrogativa para preguntas que esperan la respuesta sí/no",
        "example":""
    },
    {
        "word":"很",
        "pinyin":"hěn",
        "englishTranslation":"very",
        "spanishTranslation":"muy",
        "example":""
    },
    {
        "word":"好",
        "pinyin":"hǎo",
        "englishTranslation":"good, well, fine, OK",
        "spanishTranslation":"bien, bueno",
        "example":""
    },
    {
        "word":"你",
        "pinyin":"nǐ",
        "englishTranslation":"you",
        "spanishTranslation":"tú, vos",
        "example":""
    },
    {
        "word":"我",
        "pinyin":"wǒ",
        "englishTranslation":"I, me",
        "spanishTranslation":"yo, mi",
        "example":""
    }
]

